src/objects/Grant__c.object
<CustomObject>
    <description>Stores data about grants</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Money that will be granted</description>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <displayFormat>A{000}</displayFormat>
        <label>Grant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Line_Item__c.object
<CustomObject>
    <description>Detailed usage of grant funds</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount spent by line item</description>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Classification of the Grant Line items</description>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Grant Line Items</relationshipLabel>
        <relationshipName>Grant_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grant Line Item</label>
    <nameField>
        <displayFormat>LI#-{00000}</displayFormat>
        <label>Grant Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Grant Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Report__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount by line items</description>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Grant Reports</relationshipLabel>
        <relationshipName>Grant_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Report</label>
    <nameField>
        <displayFormat>GR-{00000}</displayFormat>
        <label>Grant Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Report_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>Grant_Line_Item_ID__r.Category__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant_Amount_Spent__c</fullName>
        <description>Grant amount spent in the referenced grant line Item</description>
        <label>Grant Amount Spent</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant_Line_Item_ID__c</fullName>
        <label>Grant Line Item ID</label>
        <referenceTo>Grant_Line_Item__c</referenceTo>
        <relationshipLabel>Grant Report Line Items</relationshipLabel>
        <relationshipName>Grant_Report_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grant_Report_ID__c</fullName>
        <label>Grant Report ID</label>
        <referenceTo>Grant_Report__c</referenceTo>
        <relationshipLabel>Grant Report Line Items</relationshipLabel>
        <relationshipName>Grant_Report_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grant Report Line Item</label>
    <nameField>
        <label>Details Link</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant Report Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GrantReportFormController.cls
public with sharing class GrantReportFormController extends SiteFormController {

  public ApexPages.StandardController sController {get; private set;}
  public Grant_Report__c grantReport {get; private set;}
  public List<GrantReportLineItem> grantReporLineItems {get; private set;}
  public Boolean alreadySubmitted {get; private set;}

  public Blob file { get; set; }
  public String fileName { get; set; }

  public GrantReportFormController(ApexPages.StandardController sController) {
    super();
    this.sController = sController;

    if (!Test.isRunningTest()) {
      sController.addFields(new List<String>{'Grant__c'});
    }

    this.grantReport = (Grant_Report__c)sController.getRecord();
    alreadySubmitted = false;
    setGrantLineItems();
  }

  public override PageReference saveLocal() {
    sController.save();
    saveReportLineItems();
    SiteFormController.saveFile(this.fileName, this.file, grantReport.Id);
    // remove file object from the page state
    file = null;
    this.alreadySubmitted = true;
    PageReference pr = ApexPages.currentPage();
    pr.setRedirect(true);
    return pr;
  }

  @TestVisible
  private void setGrantLineItems() {
    Id grantId = this.grantReport.Grant__c;
    this.grantReporLineItems = new List<GrantReportLineItem>();
    for (Grant_Line_Item__c grantLi : [SELECT Category__c, Amount__c
                                       FROM Grant_Line_Item__c
                                       WHERE Grant__c = :grantId]) {
      this.grantReporLineItems.add(new GrantReportLineItem(grantLi));
    }
  }

  public void saveReportLineItems() {
    List<Grant_Report_Line_Item__c> grantReportLIs=
  						new List<Grant_Report_Line_Item__c>();

  	for (GrantReportLineItem grantReportLi : this.grantReporLineItems) {
      Grant_Report_Line_Item__c grantReportLIObj = new Grant_Report_Line_Item__c();
      grantReportLIObj.Grant_Report_ID__c = sController.getId();
      grantReportLIObj.Grant_Line_Item_ID__c = grantReportLi.grantLi.Id;
      grantReportLIObj.Grant_Amount_Spent__c = grantReportLi.amount;
      grantReportLIs.add(grantReportLIObj);
  	}
    insert grantReportLIs;
  }

  public class GrantReportLineItem {
    public Grant_Line_Item__c grantLi {get;set;}
    public Double amount {get;set;}
    private GrantReportLineItem(Grant_Line_Item__c grantLi) {
      this.grantLi = grantLi;
    }
  }

}