src/objects/Grant__c.object
<CustomObject>
    <description>Stores data about grants</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Money that will be granted</description>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant_Category__c</fullName>
        <description>List that helps to group the grant by Category</description>
        <label>Grant Category</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Grant_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant_Status__c</fullName>
        <description>Informs about the condition of the grant</description>
        <label>Grant Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Pending Grantee Additional Info</fullName>
                </value>
                <value>
                    <fullName>Grant Signed</fullName>
                </value>
                <value>
                    <fullName>Grant Funded</fullName>
                </value>
                <value>
                    <fullName>Completed - Used Funding</fullName>
                </value>
                <value>
                    <fullName>Completed - Returned Funding</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <isActive>false</isActive>
                    <label>Accepted</label>
                </value>
                <value>
                    <fullName>Applied</fullName>
                    <isActive>false</isActive>
                    <label>Applied</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant_Type__c</fullName>
        <description>Helps to classify the grant into a group</description>
        <label>Grant Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Collaboration</fullName>
                </value>
                <value>
                    <fullName>Pay It Forward</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Donation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <displayFormat>A{000}</displayFormat>
        <label>Grant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Line_Item__c.object
<CustomObject>
    <description>Detailed usage of grant funds</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount spent by line item</description>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Classification of the Grant Line items</description>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Grant Line Items</relationshipLabel>
        <relationshipName>Grant_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grant Line Item</label>
    <nameField>
        <displayFormat>LI#-{00000}</displayFormat>
        <label>Grant Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Grant Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Report__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount by line items</description>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Grant Reports</relationshipLabel>
        <relationshipName>Grant_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <description>The date on which report was submitted by a grantee</description>
        <inlineHelpText>The date on which report was submitted by a grantee</inlineHelpText>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <label>Grant Report</label>
    <nameField>
        <displayFormat>GR-{00000}</displayFormat>
        <label>Grant Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Grant_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Educational Institutions</fullName>
    </customValue>
    <customValue>
        <fullName>End of Life Care</fullName>
    </customValue>
    <customValue>
        <fullName>Groups Promoting Meditation and Mindfulness</fullName>
    </customValue>
    <customValue>
        <fullName>Lenz Conferences</fullName>
    </customValue>
    <customValue>
        <fullName>Support for Minorities</fullName>
    </customValue>
    <customValue>
        <fullName>Prisons &amp; the Justice System</fullName>
    </customValue>
    <customValue>
        <fullName>Retreat Centers</fullName>
    </customValue>
    <customValue>
        <fullName>Support of Veterans</fullName>
    </customValue>
    <customValue>
        <fullName>At Risk Youth</fullName>
    </customValue>
    <customValue>
        <fullName>At Risk Community</fullName>
    </customValue>
    <customValue>
        <fullName>Buddhist Media</fullName>
    </customValue>
    <customValue>
        <fullName>Women in Buddhism</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grant Category</masterLabel>
</GlobalValueSet>

src/classes/GrantReportFormControllerTest.cls
@IsTest
private class GrantReportFormControllerTest {

    @IsTest
    static void testSaveLocal() {
        Grant__c grant = new Grant__c();
        grant.Amount__c = 1000;
        grant.Grant_Category__c = 'End of Life Care';
        grant.Grant_Status__c = 'Under Review';
        grant.Grant_Type__c = 'Partnership';
        insert grant;

        Grant_Line_Item__c gli = new Grant_Line_Item__c();
        gli.Category__c = 'Stuff';
        gli.Amount__c = 50;
        gli.Grant__c = grant.Id;
        insert gli;

        Grant_Report__c gr = new Grant_Report__c();
        gr.Submission_Date__c = System.today();
        gr.Grant__c = grant.Id;
        insert gr;

        ApexPages.StandardController stdGrantReport =
                new ApexPages.StandardController(gr);

        // instantiate the controller
        GrantReportFormController grantReportController =
                new GrantReportFormController(stdGrantReport);

        grantReportController.setGrantLineItems();

        // ensure that the object is saved
        grantReportController.verifyAndSave();

    }

    @IsTest
    static void testRecaptchaCallout() {
        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
        HttpResponse res = SiteFormController.makeRequest('url', 'body');

        // Verify response received contains fake values
        String contentType = res.getHeader('Content-Type');
        System.assert(contentType == 'application/json');
        String actualValue = res.getBody();
        String expectedValue = '{"success":"true"}';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, res.getStatusCode());
    }

    @IsTest
    static void testJsonParser() {
        String val = SiteFormController.getValueFromJSON('{"success":"true"}', 'success');
        System.assert(val == 'true');
    }
}