src/objects/Letter_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount  Requested by the Organization</description>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address</description>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Grant_Request_Date__c</fullName>
        <description>Approximate date when grant funding is requested</description>
        <label>Grant Request Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Contact__c</fullName>
        <description>Primary contact</description>
        <label>Main Contact</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <description>Name of the organization that is requested the grant</description>
        <label>Organization Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Qualified_Tax_Exempt_NGO_501c3_IRS__c</fullName>
        <description>Currently qualified as a tax exempt non-profit public charity per section 501 (c) 3 of the IRS</description>
        <label>Qualified Tax Exempt NGO 501c3 IRS</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Number, Street Name, Office Number. Complete mail address</description>
        <label>Street Address</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_URL__c</fullName>
        <description>Valid website</description>
        <label>Website URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Letter Of Interest</label>
    <nameField>
        <displayFormat>GR#-{00000}</displayFormat>
        <label>Grant Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LetterOfInterestFormControllerTest.cls
@IsTest
private class LetterOfInterestFormControllerTest {

    @IsTest
    static void testSaveLocal() {
        Letter_Of_Interest__c loi = new Letter_Of_Interest__c();
        loi.Amount__c = 2000;
        loi.Email__c = 'grantee@email.com';
        loi.Grant_Request_Date__c = System.today().addDays(20);
        loi.Main_Contact__c = 'Melinda Gates';
        loi.Organization_Name__c = 'Be Spiritual Now!';
        loi.Phone_Number__c = '415-111-2222';
        loi.Qualified_Tax_Exempt_NGO_501c3_IRS__c = 'Yes';
        loi.State__c = 'Georgia';
        loi.Street_Address__c = 'address';
        loi.Website_URL__c = 'www.bsn.com';
        loi.Zip_Code__c = '12345';
        loi.City__c = 'Atlanta';

        ApexPages.StandardController stdLoi =
                new ApexPages.StandardController(loi);

        // instantiate the controller
        LetterOfInterestFormController loiController =
                new LetterOfInterestFormController(stdLoi);

        // ensure that the object is saved
        loiController.verifyAndSave();

        System.assert(loiController.alreadySubmitted);
        System.assert(loiController.file == null);
        System.assert(loiController.sController.getId() != null);
    }
}